---
title: "Vulnerable Children in Grampian"
output: html_document
---

```{r, include = F}
library(here)
library(tidyverse)
library(janitor)
library(sf)
library(gt)
library(cowplot)
library(plotly)

theme_set(theme_cowplot())
```
 

-----

```{r, include = F}
#load SIMD data

simd_zones <- 
  read_csv(here("data", "SIMD+2020v2+-+datazone+lookup.csv")) 

simd_indicators <- 
  read_csv(here("data", "SIMD2020v2_indicators.csv")) %>%
   mutate(across(everything(), ~ str_remove_all(., "%")),
          across(everything(), ~ str_remove_all(., "\\*")),
          across(Total_population:nocentralheat_rate, ~ as.numeric(.)))

#load shapefiles for maps

datazone_sf <- st_read(here("data", "sc_dz_11.shp"))

#load data from 2011 census bulk files
#clean variable names to remove caps and spaces

lone_parent <- read_csv(here("data", "SNS Data Zone 2011 blk", "KS107SC.csv")) %>% 
  clean_names()

children <- read_csv(here("data", "SNS Data Zone 2011 blk", "KS106SC.csv")) %>% 
  clean_names()
```

```{r, include = F}
#join deprivation to census files
simd <- left_join(simd_indicators, simd_zones, by = c("Data_Zone" = "DZ")) %>%
  left_join(., lone_parent, by = c("Data_Zone" = "x1")) %>%
  left_join(., children, by = c("Data_Zone" = "x1"))

#add columns with lone parent stats as percentages of working age population
simd <-
simd %>%
  mutate(
    across(
      lone_parent_total:one_or_more_persons_in_household_with_a_long_term_health_problem_or_disability_no_dependent_children,
      ~ .x /all_households,
      .names = "prop_{col}"
    ),
    percentile_unemployed = ntile(prop_no_adults_in_employment_in_household_with_dependent_children, 100)
  )
```


```{r, include = F}
#pull grampian regions only

grampian <-
  simd %>%
  filter(HBname == "Grampian") 

grampian_data_zones <- pull(grampian, Data_Zone)
```


```{r, include = F}
grampian_sf <- filter(datazone_sf, DataZone %in% grampian_data_zones)

grampian_sf <-
  left_join(grampian_sf, grampian, by = c("DataZone" = "Data_Zone"))

```

## 1. Children in Grampian
### Grampian includes three local authorities
Aberdeen City has more people of working age, but all three local authorities have similar populations of children and young children.

```{r, echo = F}
la_numbers <-
grampian %>%
  group_by(LAname) %>%
  summarise(
    n_households = sum(all_households),
    total_population = sum(Total_population),
    total_working_age = sum(Working_age_population),
    prop_working_age = total_working_age/total_population,
    total_dependent_children = sum(dependent_children_in_household_all_ages),
    prop_dependent_children = total_dependent_children/total_population,
    total_under_5 = sum(dependent_children_in_household_aged_0_to_4),
    prop_under_5 = total_under_5/total_population) 

grampian %>%
  summarise(n_households = sum(all_households),
    total_population = sum(Total_population),
    total_working_age = sum(Working_age_population),
    prop_working_age = total_working_age/total_population,
    total_dependent_children = sum(dependent_children_in_household_all_ages),
    prop_dependent_children = total_dependent_children/total_population,
    total_under_5 = sum(dependent_children_in_household_aged_0_to_4),
    prop_under_5 = total_under_5/total_population)  %>%
  add_column(LAname = "Grampian", .before = "n_households") %>%
  bind_rows(la_numbers) %>%
  arrange(desc(n_households)) %>%
  gt() %>%
  fmt_number(columns = vars(n_households, total_population, total_working_age, total_dependent_children, total_under_5), decimals = 0) %>%
  fmt_percent(columns = vars(prop_working_age, prop_dependent_children, prop_under_5), decimals = 0) %>%
  cols_label(LAname = "", n_households = "Households", total_population = "Population", total_working_age = "Working age", total_dependent_children = "Dependent children", total_under_5 = "Children under 5", prop_working_age = "", prop_dependent_children = "", prop_under_5 = "") %>%
  tab_options(data_row.padding = 0)

```

## 2. Young children and deprivation 
**Mouseover or click points for area names**
Households in more deprived areas have more young children per household on average.  
The areas with the most young children per household are in the less deprived areas.

```{r}
p2 <-
  grampian %>%
  ggplot(
    aes(x = SIMD2020v2_Rank,
        y = prop_dependent_children_in_household_aged_0_to_4,
        label = DZname)
  ) +
  geom_point(alpha = 0.3) +
  geom_vline(xintercept = median(grampian$SIMD2020v2_Rank)) +
  geom_hline(yintercept = median(grampian$prop_dependent_children_in_household_aged_0_to_4)) +
  scale_x_reverse() +
  ylim(0, 0.55) +
  labs(x = "Deprivation", y = "children under 5 per household\n") +
  theme(
    legend.position = "none",
    axis.ticks = element_blank(),
    axis.text = element_blank(),
    axis.title  = element_text(size = 12)
  ) +
  annotate(
    "text",
    x = 6500,
    y = 0,
    label = "Less Deprivation\n& Fewer Young Children",
    size = 3
  ) +
  annotate(
    "text",
    x = 900,
    y = 0,
    label = "More Deprivation\n& Fewer Young Children",
    size = 3
  ) +
  annotate(
    "text",
    x = 6500,
    y = 0.55,
    label = "Less Deprivation\n& More Young Children",
    size = 3
  ) +
  annotate(
    "text",
    x = 900,
    y = 0.55,
    label = "More Deprivation\n& More Young Children",
    size = 3
  )

ggplotly(p2, tooltip = "label")
```



```{r}
simd_unemployed_plot <-
grampian %>%
  ggplot(aes(y = SIMD2020v2_Rank, 
             x = prop_no_adults_in_employment_in_household_with_dependent_children, label = DZname, 
             color = 
               (prop_no_adults_in_employment_in_household_with_dependent_children < 5.15 & SIMD2020v2_Decile == 1) |
               (prop_no_adults_in_employment_in_household_with_dependent_children < 4.50 & SIMD2020v2_Decile == 2) |
               (prop_no_adults_in_employment_in_household_with_dependent_children < 2.90 & SIMD2020v2_Decile == 3) 
  )) +
  #annotate("rect", xmin = 7, xmax = 18, ymin = 2800, ymax = 0, alpha = 0.05) +
  #annotate("text", x = 14.75, y = 2300, label = "Areas with highest deprivation\n& most lone parents", size = 3.5) +
  geom_point(alpha = 0.5) +
  scale_y_reverse() +
  scale_color_brewer(type = "qual", palette = "Dark2") +
  labs(x = "households with dependent children and no employed adults (%)", y = "\nDeprivation Rank\n") +
  theme(legend.position = "none", axis.text.y = element_blank(), axis.text = element_text(size = 10), axis.title  = element_text(size = 12))

ggplotly(simd_unemployed_plot, tooltip = "label")
```

```{r}
p <-
grampian %>%
  ggplot(aes(
    x = perc_no_adults_in_employment_in_household_with_dependent_children,
    y = perc_one_or_more_persons_in_household_with_a_long_term_health_problem_or_disability_with_dependent_children,
    label = DZname
    )) +
  geom_point(alpha = 0.5) +
  theme(legend.position = "none", axis.text = element_text(size = 10), axis.title  = element_text(size = 12))

ggplotly(p, tooltip = "label")
```




## 2. Lone Parents 

### Are lone parents more deprived? 
**Mouseover or click points for area names**

```{r, echo = F}
simd_lone_plot <-
grampian_sf %>%
  ggplot(aes(y = SIMD2020v2_Rank, x = perc_lone_parent_total, label = DZname, color = SIMD2020v2_Decile %in% c(1, 2, 3, 4) & perc_lone_parent_total >= 7)) +
  annotate("rect", xmin = 7, xmax = 18, ymin = 2800, ymax = 0, alpha = 0.05) +
  annotate("text", x = 14.75, y = 2300, label = "Areas with highest deprivation\n& most lone parents", size = 3.5) +
  geom_point(alpha = 0.5) +
  scale_y_reverse() +
  scale_color_brewer(type = "qual", palette = "Dark2") +
  labs(x = "% of working age population lone parent", y = "\nDeprivation Rank\n") +
  theme(legend.position = "none", axis.text.y = element_blank(), axis.text = element_text(size = 10), axis.title  = element_text(size = 12))

ggplotly(simd_lone_plot, tooltip = "label")
```

### Where do lone parents live?
**Mouseover or click points for area names**

```{r echo = F, message=F, fig.width=8}
#parent_plot <-
ggplot(data = grampian_sf,
       aes(y = perc_lone_parent_total, x = LAname, color = LAname, label = DZname)) + 
  geom_violin(alpha = 0.5) +
  geom_jitter(width = 0.1, alpha = 0.5) +
  geom_smooth(size = 0.5, method = "lm", se = F) +
  theme(legend.position = "none") +
  labs(x = "", y = "\nLone parents (%)\n")

ggplotly(parent_plot, tooltip = "label")
```

```{r, echo = F}
grampian %>%
  filter(Council_area == "Aberdeen City") %>%
  select(DZname, Total_population, perc_lone_parent_total, SIMD2020v2_Decile) %>%
    filter(perc_lone_parent_total >= 10) %>%
    arrange(desc(perc_lone_parent_total)) %>%
  gt() %>%
  fmt_number(columns = vars(perc_lone_parent_total), decimals = 0) %>%
  tab_header(
     title = "Areas in Aberdeen with most lone parents") %>%
   cols_label(
     DZname = "Data Zone",
     Total_population = "Population",
     perc_lone_parent_total = "Lone parents (%)",
     SIMD2020v2_Decile = "Deprivation decile") %>%
   tab_options(data_row.padding = px(1)) 
```

```{r, echo = F}
grampian %>%
  filter(Council_area == "Aberdeenshire") %>%
  select(DZname, Total_population, perc_lone_parent_total, SIMD2020v2_Decile) %>%
    filter(perc_lone_parent_total >= 10) %>%
    arrange(DZname) %>%
  gt() %>%
  fmt_number(columns = vars(perc_lone_parent_total), decimals = 0) %>%
  tab_header(
     title = "Areas in Aberdeenshire with most lone parents") %>%
   cols_label(
     DZname = "Data Zone",
     Total_population = "Population",
     perc_lone_parent_total = "Lone parents (%)",
     SIMD2020v2_Decile = "Deprivation decile") %>%
   tab_options(data_row.padding = px(1)) 
```

```{r, echo = F}
grampian %>%
  filter(Council_area == "Moray") %>%
  select(DZname, Total_population, perc_lone_parent_total, SIMD2020v2_Decile) %>%
    filter(perc_lone_parent_total >= 10) %>%
    arrange(DZname) %>%
  gt() %>%
  fmt_number(columns = vars(perc_lone_parent_total), decimals = 0) %>%
  tab_header(
     title = "Areas in Moray with most lone parents") %>%
   cols_label(
     DZname = "Data Zone",
     Total_population = "Population",
     perc_lone_parent_total = "Lone parents (%)",
     SIMD2020v2_Decile = "Deprivation decile") %>%
   tab_options(data_row.padding = px(1))
```


-----
## Sources  

Lone parent data from the 2011 Census 
https://www.scotlandscensus.gov.uk/ods-web/data-warehouse.html

Deprivation measures from Scottish Index of Multiple Deprivation 2020 version 2 
https://www.gov.scot/collections/scottish-index-of-multiple-deprivation-2020/

Shapefiles for mapping from Scottish Government
https://data.gov.uk/dataset/ab9f1f20-3b7f-4efa-9bd2-239acf63b540/data-zone-boundaries-2011

Code and data at https://github.com/JessButler/travel

Contact jessicabutler@abdn.ac.uk


